---
- name: Create LVM
  hosts: all
  tasks:
    - block:
        - name: lv 100M
          community.general.lvol:
            vg: research
            lv: data
            size: 100M
        - name: Create ext4
          community.general.filesystem:
            fstype: ext4
            dev: /dev/research/data
      rescue: 
        - name: Could not create lvm
          ansible.builtin.debug:
            msg: Could not create logical volume of that size
        - name: lv 50M
          community.general.lvol:
            vg: research
            lv: data
            size: 50
        - name: create ext4
          community.general.filesystem:
            fstype: ext4
            dev: /dev/research/data
      when: ansible_lvm.vgs.research is defined
    - debug:
        msg: Volume group does not exist
      when: ansible_lvm.vgs.research is not defined


         

