---
- name: Crreate LVM
  hosts: all
  tasks:
    - block:
        - name: Create LVM 3000M
          community.general.lvol:
            vg: researchzz
            lv: hi
            size: 3000
        - name: Create ext4
          community.general.filesystem:
            fstype: ext4
            dev: /dev/researchzz/hiii
      rescue:
        - name: Could not create lvm
          ansible.builtin.debug:
            msg: Could not create logical volume of that size
        - name: Create LVM 10M
          community.general.lvol:
            vg: researchzz
            lv: hiii
            size: 10
        - name: Create ext4
          community.general.filesystem:
            fstype: ext4
            dev: /dev/researchzz/hiii
      when: ansible_lvm.vgs.researchzz is defined
    - debug:
        msg: Volume group does not exist
      when: ansible_lvm.vgs.researchzz is not defined
