---
collections:
  - name: geerlingguy.mac
roles:
  - src: https://github.com/geerlingguy/ansible-role-haproxy.git
    name: balancer
  - src: https://github.com/geerlingguy/ansible-role-php-versions.git 
    name: phpinfo
